[control_plane]
master ansible_host=192.168.56.108

[workers]
worker01 ansible_host=192.168.56.109
worker02 ansible_host=192.168.56.110

[k8s:children]
control_plane
workers

[all:vars]
ansible_user=ansible
ansible_python_interpreter=/usr/bin/python3
